### PR TITLE
Fix blurred QRCode on iOS 7

### PR DESCRIPTION
**Pull request by Neirys**

### CODE REVIEW

**Comment by Neirys** [comment]
Solved issue #4 & #9.

**Comment by aschuch** [comment]
Thanks @Neirys. This is looking good. :boom: 
Please allow me to review this over the next few days and I'll be happy to merge :+1:

**Comment by rjyo** [comment]
Same problem on iOS9, can this be merged?

**Comment by Neirys** [comment]
I'm closing this pull request as I noticed that QRCode has a wrong orientation. I'll open a new one with a fix.

**Pull request closed without merging**
