### PR TITLE
Fix blurred QRCode on iOS 7

### PR DESCRIPTION
**Pull request by Neirys**
Same as #16 with QRCode orientation fixed.

### CODE REVIEW

**Comment by aschuch** [comment]
Thanks. I added a few comments for discussion. Otherwise, :+1:

**Comment by Neirys** [comment]
Yeah I was not sure about the `Scale` type, this can be removed and replace by `CGSize` if you wish.
When building frameworks, I'd like to have explicit access control even for `internal`s but it's a totally subjective opinion, I can remove it as well if it's not matching your coding style ;)

**Comment by aschuch** [comment]
I know where you are coming from. 
I think we should get rid of `Scale` for now, just to reduce complexity.

**Comment by Neirys** [comment]
I'll do an update asap

**Comment by aschuch** [comment]
Hey @Neirys, did you make any progress on this. If not, I can also take it from here if you want?

**Comment by Neirys** [comment]
Whoops. Sorry for that, hard time at work lately, I totally forgot this. I'll make the change the coming week-end, unless you prefer doing it before.
I also have an implementation for handling QRCode with transparent background that I'd like to propose :)

**Comment by aschuch** [comment]
No worries, we all have lots to do :smile: 
Looking forward to your changes if you get the time this weekend. Also looking forward to any other improvements and ideas you might have. :sparkler:

**Comment by Neirys** [comment]
Hey @aschuch, I've had some time at midday so I did changes we discuss about for this PR. I removed the `Scale` structure but keeping a `Scale` typealias to a tuple because I felt like using `CGSize` was kinda wrong semantically speaking. Let me know what you think about it.

**Comment by aschuch** [comment]
Awesome, thanks @Neirys.

**Pull request merged**
